---

- name: Install EPEL repo.
  yum:
    name: "{{ system_epel_repo_url }}"
    state: present

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ system_epel_repo_gpg_key_url }}"
    state: present