---

- name: Install xdebug
  yum: name={{ item }} state=present
  with_items: xdebug_packages

- name: Configure xdebug
  template: src="xdebug.ini.j2" dest="/etc/opt/rh/rh-php56/php.d/15-xdebug.ini"
  notify:
    - restart php-fpm
