require 'yaml'

# Read YAML file with box details
settings = YAML.load_file('settings.yml')

Vagrant.configure('2') do |config|

	#basic settings
	config.vm.define settings['vm_name']
	config.vm.box = settings['vm_box']

	####################
	# VM Configuration #
	####################
	config.vm.provider "virtualbox" do |v|
  	v.name = settings['vm_name']
		v.gui = false
    v.customize ["modifyvm", :id, "--ioapic", "on"]
    v.customize [ "modifyvm", :id, "--cpus", settings["proc"] ]
    v.customize [ "modifyvm", :id, "--memory", settings["ram"] ]
	end

	#################
	#   Network 		#
	#################
  config.vm.network "private_network", type: "dhcp"
	# Default HTTP port
	config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
	# MySQL port
  config.vm.network "forwarded_port", guest: 3306, host: 3307

	#################
	# Synced folder #
	#################
	config.vm.synced_folder "./", "/vagrant", id: "vagrant-root"
	if settings["synced"]
	    settings["synced"]["folders"].each do |sf_name, sf|
	        config.vm.synced_folder sf["host_path"], sf["guest_path"], type:"nfs"
	    end
	end

	#################
	# Provisionning #
	#################
	config.vm.provision "platform", type:"ansible_local" do |ansible|
	    ansible.playbook = "/vagrant/provisionning/ansible/build_bls_dev_platform.yml"
	    ansible.inventory_path = "/vagrant/provisionning/ansible/environment/DEV/DEV"
	    ansible.limit = "all"
	end



end
